### ISSUE TITLE
Deadlock on synchrounous sentiment

### ISSUE THREAD

**Issue by iudelsmann** [Microsoft/Cognitive-TextAnalytics-Windows#25]
Hello,

I've just started working with this SDK to analyse the sentiment of texts, in a chatbot conversation, and found a problem on SentimentClient.cs. The synchronous GetSentiment method returns a `Task.Result` which causes a deadlock and my program hangs. I beleive this method should be fixed to use `Task.Run(() => ...).Result` or maybe call `ConfigureAwait(false)`. Anyway I'm using the async method so this is not impacting me.

Thank you.

**Comment by adgroc** [comment]
Issue resolved in migration to .NET Standard. This project is now in a new [repo](https://github.com/Microsoft/Cognitive-TextAnalytics-DotNet).
