### ISSUE TITLE
Please, merge this project with https://github.com/Microsoft/Cognitive-TextAnalytics-DotNetCore using .net standard

### ISSUE THREAD

**Issue by SychevIgor** [Microsoft/Cognitive-TextAnalytics-Windows#27]
The code of client library 100% identical between projects. At least via .net standard 2.0 please remo this duplication

**Comment by adgroc** [comment]
This project has been moved to a new [repo](https://github.com/Microsoft/Cognitive-TextAnalytics-DotNet), and it has been migrated to .NET Standard.
